# render.yaml

services:
- name: web
  buildCommand: |
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
  startCommand: gunicorn marketproject.wsgi:application -b 0.0.0.0:$PORT
